### ISSUE TITLE
gitian 0.20.1

### ISSUE THREAD

**Issue by decryp2kanon** [sugarchain-project/yumekawa#12]
https://gist.github.com/decryp2kanon/1612130b06e1310367675365667843f2

https://gist.github.com/laanwj/c62e101bfd68718f0686926dfd10666b

https://github.com/bitcoin/bitcoin/issues/14068

https://codedocs.xyz/BlocknetDX/BlockDX/md_doc_gitian-building.html

# FAILED
- debian 8.10
- ubuntu 18.04
- debian 9.5
- debian 10

# PROBLEM
`./gitian-build.py --setup`
```bash
base-bionic-amd64 already exists, please remove it first
Traceback (most recent call last):
  File "./gitian-build.py", line 262, in <module>
    main()
  File "./gitian-build.py", line 198, in main
    setup()
  File "./gitian-build.py", line 42, in setup
    subprocess.check_call(make_image_prog)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bin/make-base-vm', '--suite', 'bionic', '--arch', 'amd64', '--lxc']' returned non-zero exit status 1
```

**Comment by decryp2kanon** [comment]
https://github.com/bitcoin/bitcoin/issues/13991

try

**Comment by decryp2kanon** [comment]
# Win failed
`./gitian-build.py -j 4 -m 4000 --os w --detach-sign --no-commit -b decryp2kanon 0.20.1`
```bash
--- Building for bionic amd64 ---
Stopping target if it is up
Making a new image copy
cp: cannot stat 'base-bionic-amd64': No such file or directory
bin/gbuild:23:in `system!': failed to run make-clean-vm --suite bionic --arch amd64 (RuntimeError)
	from bin/gbuild:60:in `build_one_configuration'
	from bin/gbuild:336:in `block (2 levels) in <main>'
	from bin/gbuild:331:in `each'
	from bin/gbuild:331:in `block in <main>'
	from bin/gbuild:329:in `each'
	from bin/gbuild:329:in `<main>'
Traceback (most recent call last):
  File "./gitian-build.py", line 262, in <module>
    main()
  File "./gitian-build.py", line 250, in main
    build()
  File "./gitian-build.py", line 69, in build
    subprocess.check_call(['bin/gbuild', '-j', args.jobs, '-m', args.memory, '--commit', 'bitcoin='+args.commit, '--url', 'bitcoin='+args.url, '../bitcoin/contrib/gitian-descriptors/gitian-win.yml'])
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bin/gbuild', '-j', '4', '-m', '4000', '--commit', 'bitcoin=v0.20.1', '--url', 'bitcoin=https://github.com/bitcoin/bitcoin', '../bitcoin/contrib/gitian-descriptors/gitian-win.yml']' returned non-zero exit status 1
```

# MacOS failed
```bash
./gitian-build.py -j 4 -m 4000 --os m --detach-sign --no-commit -b decryp2kanon 0.20.1
Cannot build for MacOS, SDK does not exist. Will build for other OSes
v0.20.1
```

**Comment by decryp2kanon** [comment]
# fedora 29

```bash
$ ./gitian-build.py --setup
Traceback (most recent call last):
  File "./gitian-build.py", line 262, in <module>
    main()
  File "./gitian-build.py", line 178, in main
    args.is_bionic = b'bionic' in subprocess.check_output(['lsb_release', '-cs'])
  File "/usr/lib64/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'lsb_release': 'lsb_release'
```

**Comment by decryp2kanon** [comment]
Apple SDK
https://stackoverflow.com/questions/10335747/how-to-download-xcode-dmg-or-xip-file
https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_11.3.1/Xcode_11.3.1.xip

**Comment by decryp2kanon** [comment]
# ubuntu 18.04 :heavy_check_mark: 
OK
https://gist.github.com/decryp2kanon/67730da9e5f78bfb07f555d106b36686

**Comment by decryp2kanon** [comment]
# DEBIAN 9 and 10  problem
https://github.com/devrandom/gitian-builder/issues/224

**Comment by decryp2kanon** [comment]
https://gist.github.com/decryp2kanon/67730da9e5f78bfb07f555d106b36686

OK
