### ISSUE TITLE
python tests

### ISSUE THREAD

**Issue by decryp2kanon** [sugarchain-project/yumekawa#23]
# error
![image](https://user-images.githubusercontent.com/60179867/94523702-969b9900-01ff-11eb-814c-d0738039ba3d.png)
```bash
$ ./test/functional/test_runner.py --jobs=1 --loglevel=DEBUG

43/168 - rpc_getchaintips.py failed, Duration: 0 s

stdout:
2020-09-29T06:10:51.608000Z TestFramework (DEBUG): PRNG seed is: 6600466007959688468
2020-09-29T06:10:51.609000Z TestFramework (DEBUG): Setting up network thread
2020-09-29T06:10:51.609000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20200929_015305/rpc_getchaintips_125
2020-09-29T06:10:51.609000Z TestFramework (DEBUG): Copy cache directory /home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/cache/node0 to node 0
2020-09-29T06:10:51.626000Z TestFramework (DEBUG): Copy cache directory /home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/cache/node0 to node 1
2020-09-29T06:10:51.642000Z TestFramework (DEBUG): Copy cache directory /home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/cache/node0 to node 2
2020-09-29T06:10:51.658000Z TestFramework (DEBUG): Copy cache directory /home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/cache/node0 to node 3
2020-09-29T06:10:51.676000Z TestFramework.node0 (DEBUG): litecoind started, waiting for RPC to come up
2020-09-29T06:10:51.679000Z TestFramework.node1 (DEBUG): litecoind started, waiting for RPC to come up
2020-09-29T06:10:51.681000Z TestFramework.node2 (DEBUG): litecoind started, waiting for RPC to come up
2020-09-29T06:10:51.683000Z TestFramework.node3 (DEBUG): litecoind started, waiting for RPC to come up
2020-09-29T06:10:51.934000Z TestFramework.node0 (DEBUG): Stopping node
2020-09-29T06:10:51.934000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 503, in start_nodes
    node.wait_for_rpc_connection()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_node.py", line 221, in wait_for_rpc_connection
    'litecoind exited with status {} during initialization'.format(self.process.returncode)))
test_framework.test_node.FailedToStartError: [node 0] litecoind exited with status 1 during initialization

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 117, in main
    self.setup()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 249, in setup
    self.setup_network()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 343, in setup_network
    self.setup_nodes()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 371, in setup_nodes
    self.start_nodes()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 506, in start_nodes
    self.stop_nodes()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 522, in stop_nodes
    node.stop_node(wait=wait)
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_node.py", line 319, in stop_node
    self.stop(wait=wait)
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_node.py", line 179, in __getattr__
    assert self.rpc_connected and self.rpc is not None, self._node_msg("Error: no RPC connection")
AssertionError: [node 0] Error: no RPC connection
2020-09-29T06:10:51.936000Z TestFramework (DEBUG): Closing down network thread
2020-09-29T06:10:51.986000Z TestFramework (INFO): Stopping nodes
2020-09-29T06:10:51.987000Z TestFramework.node0 (DEBUG): Stopping node
[node 3] Cleaning up leftover process
[node 2] Cleaning up leftover process
[node 1] Cleaning up leftover process
[node 0] Cleaning up leftover process


stderr:
Traceback (most recent call last):
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/rpc_getchaintips.py", line 63, in <module>
    GetChainTipsTest ().main ()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 141, in main
    exit_code = self.shutdown()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 265, in shutdown
    self.stop_nodes()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 522, in stop_nodes
    node.stop_node(wait=wait)
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_node.py", line 319, in stop_node
    self.stop(wait=wait)
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_node.py", line 179, in __getattr__
    assert self.rpc_connected and self.rpc is not None, self._node_msg("Error: no RPC connection")
AssertionError: [node 0] Error: no RPC connection


44/168 - rpc_misc.py passed, Duration: 1 s
```
# but single testing is fine. :thinking: 

```bash
$ ./test/functional/test_runner.py --jobs=1 --loglevel=DEBUG rpc_getchaintips.py
Temporary test directory at /tmp/test_runner_₿_🏃_20200929_024604
Running Unit Tests for Test Framework Modules
.......
----------------------------------------------------------------------
Ran 7 tests in 0.008s

OK
Remaining jobs: [rpc_getchaintips.py]
1/1 - rpc_getchaintips.py passed, Duration: 2 s

TEST                | STATUS    | DURATION

rpc_getchaintips.py | ✓ Passed  | 2 s

ALL                 | ✓ Passed  | 2 s (accumulated) 
Runtime: 2 s
```

**Comment by decryp2kanon** [comment]
https://travis-ci.org/github/sugarchain-project/yumekawa/jobs/731202972
```bash
feature_backwards_compatibility.py    | ✖ Failed  | 1 s
ALL                                   | ✖ Failed  | 2777 s (accumulated) 
Runtime: 725 s
```

**Comment by decryp2kanon** [comment]
```bash
$ ./test/functional/test_runner.py --jobs=4 --loglevel=DEBUG --previous-releases --coverage --extended feature_backwards_compatibility.py
Temporary test directory at /tmp/test_runner_₿_🏃_20200929_045502
Running Unit Tests for Test Framework Modules
.......
----------------------------------------------------------------------
Ran 7 tests in 0.008s

OK
Initializing coverage directory at /tmp/coverage4gb7ltpw
Remaining jobs: [feature_backwards_compatibility.py]
1/1 - feature_backwards_compatibility.py failed, Duration: 0 s

stdout:
2020-09-29T08:55:03.057000Z TestFramework (DEBUG): PRNG seed is: 6711036426748498187
2020-09-29T08:55:03.057000Z TestFramework (DEBUG): Setting up network thread
2020-09-29T08:55:03.058000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 117, in main
    self.setup()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 247, in setup
    self.skip_test_if_missing_module()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/feature_backwards_compatibility.py", line 49, in skip_test_if_missing_module
    self.skip_if_no_previous_releases()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 747, in skip_if_no_previous_releases
    if not self.has_previous_releases():
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 755, in has_previous_releases
    self.options.previous_releases_path))
AssertionError: Force test of previous releases but releases missing: /home/ak/git/SUGAR/SUGARCHAIN/yumekawa/releases
2020-09-29T08:55:03.058000Z TestFramework (DEBUG): Closing down network thread
2020-09-29T08:55:03.109000Z TestFramework (INFO): Stopping nodes
2020-09-29T08:55:03.109000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20200929_045502/feature_backwards_compatibility_0
2020-09-29T08:55:03.109000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20200929_045502/feature_backwards_compatibility_0/test_framework.log
2020-09-29T08:55:03.109000Z TestFramework (ERROR): 
2020-09-29T08:55:03.110000Z TestFramework (ERROR): Hint: Call /home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20200929_045502/feature_backwards_compatibility_0' to consolidate all logs
2020-09-29T08:55:03.110000Z TestFramework (ERROR): 
2020-09-29T08:55:03.110000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2020-09-29T08:55:03.110000Z TestFramework (ERROR): https://github.com/litecoin-project/litecoin/issues
2020-09-29T08:55:03.110000Z TestFramework (ERROR): 


stderr:



TEST                               | STATUS    | DURATION

feature_backwards_compatibility.py | ✖ Failed  | 0 s

ALL                                | ✖ Failed  | 0 s (accumulated) 
Runtime: 0 s

Traceback (most recent call last):
  File "./test/functional/test_runner.py", line 751, in <module>
    main()
  File "./test/functional/test_runner.py", line 402, in main
    use_term_control=args.ansi,
  File "./test/functional/test_runner.py", line 496, in run_tests
    coverage_passed = coverage.report_rpc_coverage()
  File "./test/functional/test_runner.py", line 703, in report_rpc_coverage
    uncovered = self._get_uncovered_rpc_commands()
  File "./test/functional/test_runner.py", line 733, in _get_uncovered_rpc_commands
    raise RuntimeError("No coverage reference found")
RuntimeError: No coverage reference found
```

**Comment by decryp2kanon** [comment]
`./test/functional/test_runner.py --jobs=4 --loglevel=DEBUG --previous-releases --extended feature_backwards_compatibility.py`

**Comment by decryp2kanon** [comment]
https://travis-ci.org/github/sugarchain-project/yumekawa/jobs/731215589
```
WARNING! The following scripts are not being run: ['feature_backwards_compatibility.py']. Check the test lists in test_runner.py.
```

**Comment by decryp2kanon** [comment]
https://travis-ci.org/github/sugarchain-project/yumekawa/jobs/731224858
```bash
$ ./test/functional/test_runner.py --jobs=4 --loglevel=DEBUG --previous-releases --coverage --extended wallet_upgradewallet.py 
Temporary test directory at /tmp/test_runner_₿_🏃_20200929_063013
WARNING! The following scripts are not being run: ['feature_backwards_compatibility.py']. Check the test lists in test_runner.py.
Running Unit Tests for Test Framework Modules
.......
----------------------------------------------------------------------
Ran 7 tests in 0.008s

OK
Initializing coverage directory at /tmp/coverageok82rt3b
Remaining jobs: [wallet_upgradewallet.py]
1/1 - wallet_upgradewallet.py failed, Duration: 0 s

stdout:
2020-09-29T10:30:13.969000Z TestFramework (DEBUG): PRNG seed is: 207664040093496443
2020-09-29T10:30:13.970000Z TestFramework (DEBUG): Setting up network thread
2020-09-29T10:30:13.970000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 117, in main
    self.setup()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 247, in setup
    self.skip_test_if_missing_module()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/wallet_upgradewallet.py", line 37, in skip_test_if_missing_module
    self.skip_if_no_previous_releases()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 747, in skip_if_no_previous_releases
    if not self.has_previous_releases():
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 755, in has_previous_releases
    self.options.previous_releases_path))
AssertionError: Force test of previous releases but releases missing: /home/ak/git/SUGAR/SUGARCHAIN/yumekawa/releases
2020-09-29T10:30:13.971000Z TestFramework (DEBUG): Closing down network thread
2020-09-29T10:30:14.021000Z TestFramework (INFO): Stopping nodes
2020-09-29T10:30:14.021000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20200929_063013/wallet_upgradewallet_0
2020-09-29T10:30:14.021000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20200929_063013/wallet_upgradewallet_0/test_framework.log
2020-09-29T10:30:14.022000Z TestFramework (ERROR): 
2020-09-29T10:30:14.022000Z TestFramework (ERROR): Hint: Call /home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20200929_063013/wallet_upgradewallet_0' to consolidate all logs
2020-09-29T10:30:14.022000Z TestFramework (ERROR): 
2020-09-29T10:30:14.022000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2020-09-29T10:30:14.022000Z TestFramework (ERROR): https://github.com/litecoin-project/litecoin/issues
2020-09-29T10:30:14.022000Z TestFramework (ERROR): 


stderr:



TEST                    | STATUS    | DURATION

wallet_upgradewallet.py | ✖ Failed  | 0 s

ALL                     | ✖ Failed  | 0 s (accumulated) 
Runtime: 0 s

Traceback (most recent call last):
  File "./test/functional/test_runner.py", line 752, in <module>
    main()
  File "./test/functional/test_runner.py", line 402, in main
    use_term_control=args.ansi,
  File "./test/functional/test_runner.py", line 496, in run_tests
    coverage_passed = coverage.report_rpc_coverage()
  File "./test/functional/test_runner.py", line 704, in report_rpc_coverage
    uncovered = self._get_uncovered_rpc_commands()
  File "./test/functional/test_runner.py", line 734, in _get_uncovered_rpc_commands
    raise RuntimeError("No coverage reference found")
RuntimeError: No coverage reference found
```

**Comment by decryp2kanon** [comment]
```bash
$ ./test/functional/test_runner.py --jobs=4 --loglevel=DEBUG --previous-releases --coverage --extended mempool_compatibility.py
Temporary test directory at /tmp/test_runner_₿_🏃_20200929_071141
WARNING! The following scripts are not being run: ['wallet_upgradewallet.py', 'feature_backwards_compatibility.py']. Check the test lists in test_runner.py.
Running Unit Tests for Test Framework Modules
.......
----------------------------------------------------------------------
Ran 7 tests in 0.008s

OK
Initializing coverage directory at /tmp/coverageso8c6ntk
Remaining jobs: [mempool_compatibility.py]
1/1 - mempool_compatibility.py failed, Duration: 0 s

stdout:
2020-09-29T11:11:41.528000Z TestFramework (DEBUG): PRNG seed is: 3291821775783265060
2020-09-29T11:11:41.528000Z TestFramework (DEBUG): Setting up network thread
2020-09-29T11:11:41.528000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 117, in main
    self.setup()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 247, in setup
    self.skip_test_if_missing_module()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/mempool_compatibility.py", line 27, in skip_test_if_missing_module
    self.skip_if_no_previous_releases()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 747, in skip_if_no_previous_releases
    if not self.has_previous_releases():
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 755, in has_previous_releases
    self.options.previous_releases_path))
AssertionError: Force test of previous releases but releases missing: /home/ak/git/SUGAR/SUGARCHAIN/yumekawa/releases
2020-09-29T11:11:41.529000Z TestFramework (DEBUG): Closing down network thread
2020-09-29T11:11:41.579000Z TestFramework (INFO): Stopping nodes
2020-09-29T11:11:41.579000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20200929_071141/mempool_compatibility_0
2020-09-29T11:11:41.579000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20200929_071141/mempool_compatibility_0/test_framework.log
2020-09-29T11:11:41.580000Z TestFramework (ERROR): 
2020-09-29T11:11:41.580000Z TestFramework (ERROR): Hint: Call /home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20200929_071141/mempool_compatibility_0' to consolidate all logs
2020-09-29T11:11:41.580000Z TestFramework (ERROR): 
2020-09-29T11:11:41.580000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2020-09-29T11:11:41.580000Z TestFramework (ERROR): https://github.com/litecoin-project/litecoin/issues
2020-09-29T11:11:41.580000Z TestFramework (ERROR): 


stderr:



TEST                     | STATUS    | DURATION

mempool_compatibility.py | ✖ Failed  | 0 s

ALL                      | ✖ Failed  | 0 s (accumulated) 
Runtime: 0 s

Traceback (most recent call last):
  File "./test/functional/test_runner.py", line 751, in <module>
    main()
  File "./test/functional/test_runner.py", line 402, in main
    use_term_control=args.ansi,
  File "./test/functional/test_runner.py", line 496, in run_tests
    coverage_passed = coverage.report_rpc_coverage()
  File "./test/functional/test_runner.py", line 703, in report_rpc_coverage
    uncovered = self._get_uncovered_rpc_commands()
  File "./test/functional/test_runner.py", line 733, in _get_uncovered_rpc_commands
    raise RuntimeError("No coverage reference found")
RuntimeError: No coverage reference found
```

**Comment by decryp2kanon** [comment]
```bash
40/168 - wallet_txn_clone.py failed, Duration: 0 s

stdout:
2020-09-29T10:40:04.689000Z TestFramework (DEBUG): PRNG seed is: 6777895638651036315
2020-09-29T10:40:04.689000Z TestFramework (DEBUG): Setting up network thread
2020-09-29T10:40:04.689000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20200929_063305/wallet_txn_clone_125
2020-09-29T10:40:04.689000Z TestFramework (DEBUG): Copy cache directory /home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/cache/node0 to node 0
2020-09-29T10:40:04.706000Z TestFramework (DEBUG): Copy cache directory /home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/cache/node0 to node 1
2020-09-29T10:40:04.723000Z TestFramework (DEBUG): Copy cache directory /home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/cache/node0 to node 2
2020-09-29T10:40:04.740000Z TestFramework (DEBUG): Copy cache directory /home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/cache/node0 to node 3
2020-09-29T10:40:04.763000Z TestFramework.node0 (DEBUG): litecoind started, waiting for RPC to come up
2020-09-29T10:40:04.765000Z TestFramework.node1 (DEBUG): litecoind started, waiting for RPC to come up
2020-09-29T10:40:04.767000Z TestFramework.node2 (DEBUG): litecoind started, waiting for RPC to come up
2020-09-29T10:40:04.769000Z TestFramework.node3 (DEBUG): litecoind started, waiting for RPC to come up
2020-09-29T10:40:05.020000Z TestFramework.node0 (DEBUG): Stopping node
2020-09-29T10:40:05.020000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 503, in start_nodes
    node.wait_for_rpc_connection()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_node.py", line 221, in wait_for_rpc_connection
    'litecoind exited with status {} during initialization'.format(self.process.returncode)))
test_framework.test_node.FailedToStartError: [node 0] litecoind exited with status 1 during initialization

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 117, in main
    self.setup()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 249, in setup
    self.setup_network()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/wallet_txn_clone.py", line 32, in setup_network
    super().setup_network()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 343, in setup_network
    self.setup_nodes()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 371, in setup_nodes
    self.start_nodes()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 506, in start_nodes
    self.stop_nodes()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 522, in stop_nodes
    node.stop_node(wait=wait)
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_node.py", line 319, in stop_node
    self.stop(wait=wait)
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_node.py", line 179, in __getattr__
    assert self.rpc_connected and self.rpc is not None, self._node_msg("Error: no RPC connection")
AssertionError: [node 0] Error: no RPC connection
2020-09-29T10:40:05.022000Z TestFramework (DEBUG): Closing down network thread
2020-09-29T10:40:05.072000Z TestFramework (INFO): Stopping nodes
2020-09-29T10:40:05.072000Z TestFramework.node0 (DEBUG): Stopping node
[node 3] Cleaning up leftover process
[node 2] Cleaning up leftover process
[node 1] Cleaning up leftover process
[node 0] Cleaning up leftover process


stderr:
Traceback (most recent call last):
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/wallet_txn_clone.py", line 145, in <module>
    TxnMallTest().main()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 141, in main
    exit_code = self.shutdown()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 265, in shutdown
    self.stop_nodes()
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_framework.py", line 522, in stop_nodes
    node.stop_node(wait=wait)
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_node.py", line 319, in stop_node
    self.stop(wait=wait)
  File "/home/ak/git/SUGAR/SUGARCHAIN/yumekawa/test/functional/test_framework/test_node.py", line 179, in __getattr__
    assert self.rpc_connected and self.rpc is not None, self._node_msg("Error: no RPC connection")
AssertionError: [node 0] Error: no RPC connection
```
