### ISSUE TITLE
gitian failed when windows

### ISSUE THREAD

**Issue by decryp2kanon** [sugarchain-project/yumekawa#30]
`$ ./gitian-build.py -j 14 -m 10000 --os lwm --detach-sign --no-commit -b decryp2kanon 0.20.99-rc2`

```bash
Compiling 0.20.99-rc2 Windows
--- Building for bionic amd64 ---
Stopping target if it is up
Making a new image copy
sudo: unable to resolve host gitian: Resource temporarily unavailable
Reading package lists... Done
Building dependency tree... Done
The following packages will be REMOVED:
  rsyslog*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 1466 kB disk space will be freed.
(Reading database ... 18583 files and directories currently installed.)
Removing rsyslog (8.32.0-1ubuntu4) ...
invoke-rc.d: could not determine current runlevel
 * Stopping enhanced syslogd rsyslogd
   ...done.
(Reading database ... 18525 files and directories currently installed.)
Purging configuration files for rsyslog (8.32.0-1ubuntu4) ...
dpkg: warning: while removing rsyslog, directory '/etc/apparmor.d/local' not empty so not removed
Processing triggers for systemd (237-3ubuntu10) ...
Adding 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
Adding 'local diversion of /usr/bin/ischroot to /usr/bin/ischroot.distrib'
Adding 'local diversion of /usr/sbin/policy-rc.d to /usr/sbin/policy-rc.d.distrib'
Starting target
Checking if target is up
Preparing build environment
Updating apt-get repository (log in var/install.log)
Installing additional packages (log in var/install.log)
Upgrading system, may take a while (log in var/install.log)
Creating package manifest
Creating build script (var/build-script)
Running build script (log in var/build.log)
Traceback (most recent call last):
	6: from bin/gbuild:332:in `<main>'
	5: from bin/gbuild:332:in `each'
	4: from bin/gbuild:334:in `block in <main>'
	3: from bin/gbuild:334:in `each'
	2: from bin/gbuild:339:in `block (2 levels) in <main>'
	1: from bin/gbuild:185:in `build_one_configuration'
bin/gbuild:23:in `system!': failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)
Traceback (most recent call last):
  File "./gitian-build.py", line 262, in <module>
    main()
  File "./gitian-build.py", line 250, in main
    build()
  File "./gitian-build.py", line 69, in build
    subprocess.check_call(['bin/gbuild', '-j', args.jobs, '-m', args.memory, '--commit', 'sugarchain='+args.commit, '--url', 'sugarchain='+args.url, '../sugarchain/contrib/gitian-descriptors/gitian-win.yml'])
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bin/gbuild', '-j', '14', '-m', '10000', '--commit', 'sugarchain=v0.20.99-rc2', '--url', 'sugarchain=https://github.com/sugarchain-project/yumekawa', '../sugarchain/contrib/gitian-descriptors/gitian-win.yml']' returned non-zero exit status 1.
```

**Comment by decryp2kanon** [comment]
just need more RAM
